export const REPORT_HEADERS:readonly string[]=["Date", "Restaurant ID", "Outlet name", "Successful Orders", "Gross Sales", "Delivery Sales", "Pickup Sales", "Orders count", "Cancelled Orders", "Online Orders", "Cash Orders", "Delivery Orders", "Pickup Orders", "Pro Orders", "Pro Revenue", "Items count", "Unavailable time duration (Minutes)", "Unavailable Time Duration Rate", "Scheduled Open Time (Minutes)", "Unavailable time reason", "Unavailable Time Duration count", "Orders with Avoidable cancellations", "Avoidable cancellation rate", "Revenue loss from rejections", "Avoidable Cancellation Reason", "Avoidable cancellation count", "Sales loss", "Average preparation time (minutes)", "Orders marked as ready", "Orders marked rate", "Total AWT Duration (Minutes)", "Orders with AWT", "Order with AWT Fee", "Total Fee applied", "Orders in Bucket1: < 5 minutes", "Orders with fees in Bucket1: < 5 minutes", "Orders in Bucket2: >= 5 Mins and < 10 Mins", "Orders with fees in Bucket2: >= 5 Mins and < 10 Mins", "Orders in Bucket3: >= 10 Mins", "Orders with fees in Bucket3: >= 10 Mins", "Total customer complaints received", "Customer Complaint rate", "Customer Complaint Reason", "Customer Complaint Contacts", "Own delivery contacts count", "Vendor delivery contacts counts", "Orders from new customers", "Orders from new customers rate", "Orders from returning customers", "Orders from returning customers rate", "Impressions", "Viewed your menu", "Added items to cart", "Placed an order"];
const identity=(value:string)=>value.toLowerCase().replace(/\s+/g,' ').trim();
const aliases=new Map(REPORT_HEADERS.map(header=>[identity(header),header]));
aliases.set('new customer orders','Orders from new customers');
aliases.set('returning customer orders','Orders from returning customers');
export function canonicalReportHeader(header:string):string{return aliases.get(identity(header))??header;}
export function canonicalReportHeaders(headers:string[]):string[]{return headers.map(canonicalReportHeader);}
/** SQL mapping runs before newest-non-null selection, preserving raw revisions. */
export const canonicalHeaderSql='CASE '+[...aliases].map(([source,target])=>"WHEN lower(regexp_replace(btrim(e.key), '[[:space:]]+', ' ', 'g'))='"+source.replace("'","''")+"' THEN '"+target.replace("'","''")+"'").join(' ')+' ELSE e.key END';
