import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateOperations} from '../src/services/deliveroo-operations-model.ts';import {readDeliverooOperations,scopeDeliverooOperations,restrictDeliverooOperations} from '../src/services/deliveroo-operations.ts';
const snapshot=JSON.parse(fs.readFileSync('tests/fixtures/operations-7.json','utf8'));
const db=(payload:any)=>({query:async()=>({rows:payload?[{payload}]:[]})});
test('operations read preserves native rates and normalized branch identities',async()=>{const data=await readDeliverooOperations(7,db(snapshot));assert.equal(data.state,'SUCCESS');assert.equal(data.snapshot.rows.length,16);const r=data.snapshot.rows.find((r:any)=>r.storeId==='621382');assert.equal(r.storeName,'FRB Kabab — Al Wasl');assert.equal(r.service.latePrepared.pct,66.67);assert.equal(r.service.inaccurate.total,1);assert.equal(r.metrics.find((m:any)=>m.name==='prep_time').total,19.0533);assert.equal((await readDeliverooOperations(30,db(snapshot))).state,'ERROR');});
test('missing storage is empty and corrupted coverage is never partially exposed',async()=>{assert.equal((await readDeliverooOperations(7,db(null))).state,'EMPTY');const corrupt=structuredClone(snapshot);corrupt.rows.pop();assert.throws(()=>validateOperations(corrupt));assert.equal((await readDeliverooOperations(7,db(corrupt))).state,'ERROR');assert.equal((await readDeliverooOperations(7,{query:async()=>{throw {code:'42P01'};}})).state,'EMPTY');await assert.rejects(()=>readDeliverooOperations(1,db(snapshot)));});
test('operations reuse rating identities, exclude disabled branches and restrict brand/branch users',async()=>{
 const data=await readDeliverooOperations(7,db(snapshot)),register:any=async(sources:any[])=>new Map(sources.map(s=>[s.sourceType+'\0'+s.sourceId,{id:s.sourceId.split(';').at(-1),brand:s.storeName.split(' — ')[0],canonicalKey:s.sourceId,active:!s.sourceId.endsWith(';621382')}]));
 const user:any={id:'test',username:'test',displayName:'Test',role:'brand_manager',scopes:[{type:'brand',key:'FRB Kabab'}],mustChangePassword:false,isOwner:false};
 const scoped=await scopeDeliverooOperations(data,user,register);assert.deepEqual(scoped.snapshot.rows.map((r:any)=>r.storeId),['621379','621372','621374']);assert.equal(scoped.snapshot.storeCount,3);
 user.role='branch_manager';user.scopes=[{type:'branch',key:'621364'}];const branch=await scopeDeliverooOperations(data,user,register);assert.equal(branch.snapshot.rows.length,1);assert.equal(branch.snapshot.rows[0].storeId,'621364');assert.equal(restrictDeliverooOperations(data,new Set()).snapshot.rows.length,0);
});
