import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {talabatZeroOrderDay,growthNumber,growthRow,readTalabatGrowth,readKeetaGrowth,readNoonGrowth,fetchGrowth} from '../src/services/growth.ts';
import {createCloudHandler} from '../src/cloud-api.ts';
import {scopeKeetaSnapshot} from '../src/services/keeta-snapshot-scope.ts';
const now=new Date('2026-10-07T09:00:00Z'),p={from:'2026-09-30',to:'2026-10-06',previousFrom:'2026-09-23',previousTo:'2026-09-29'};
const rows=()=>Array.from({length:14},(_,i)=>({source_key:'source',report_date:new Date(Date.parse('2026-09-23')+i*86400000).toISOString().slice(0,10),store_id:'1',present:true,orders:i<7?'20':'10',sales:i<7?'1200':'500'}));
const talabat=()=>({state:'SUCCESS',reportDate:p.to,receivedAt:now.toISOString(),rows:[{storeId:'1',storeName:'Kabab Fareej — Barsha',present:true,values:{'Successful Orders':'10','Gross Sales':'500'}}]});
test('Keeta direct historical comparison removes dependency on an old snapshot and stays scoped',async()=>{
 const comparison={from:p.previousFrom,to:p.previousTo,sales:8029,orders:110,verifiedBy:'SOURCE_CHANGE_RATIOS'};
 const data:any={state:'SUCCESS',snapshot:{periodFrom:p.from,periodTo:p.to,comparisonFrom:p.previousFrom,comparisonTo:p.previousTo,observedAt:now.toISOString(),shops:[{shopId:'1',business:{shop_income:'10,183.50',shop_valid_order_num:'130'},businessComparison:comparison},{shopId:'2',shopName:'Forbidden',businessComparison:comparison}]}};
 data.snapshot=scopeKeetaSnapshot(data.snapshot,new Set(['1']));
 const result=await readKeetaGrowth(data,{query:async()=>assert.fail('No historical database read needed')},now);
 assert.equal(result.rows.length,1);assert.equal(result.rows[0].previous.sales,8029);assert.equal(result.rows[0].ordersDelta,20);assert.equal(result.rows[0].delta,2154.5);assert.ok(!JSON.stringify(result).includes('Forbidden'));
 for(const invalid of [{...comparison,from:'2026-09-24'},{...comparison,verifiedBy:'ESTIMATE'},{...comparison,orders:110.5}]){
  data.snapshot.shops[0].businessComparison=invalid;
  const missing=await readKeetaGrowth(data,{query:async()=>({rows:[]})},now);
  assert.equal(missing.rows[0].eligible,false);
 }
});
test('Growth parses sales without interpreting unknowns as zero',()=>{for(const v of [null,undefined,'','AED 100','10%','1,2','-2','Infinity'])assert.equal(growthNumber(v),null);assert.equal(growthNumber('1,250.25'),1250.25);assert.equal(growthNumber(0),0);});
test('Growth decomposition reconciles changes, zero baseline does not invent percentage',()=>{const r=growthRow('id','name',p,{sales:500,orders:10},{sales:1200,orders:20});assert.equal(r.delta,-700);assert.equal(r.orderEffect!+r.basketEffect!,r.delta);assert.equal(r.aov,50);assert.equal(r.ordersDelta,-10);const first=growthRow('id','name',p,{sales:500,orders:10},{sales:0,orders:0});assert.equal(first.deltaPercent,null);assert.equal(first.orderEffect,null);assert.equal(first.eligible,true);const closed=growthRow('id','name',p,{sales:0,orders:0},{sales:500,orders:10});assert.equal(closed.delta,-500);assert.equal(closed.aov,null);assert.equal(growthRow('id','name',p,{sales:20,orders:0},{sales:10,orders:1}).eligible,false);});
test('Talabat requires fourteen distinct valid daily branch observations and verifies controlling source',async()=>{const data=rows(),db={query:async(q:any)=>{assert.deepEqual(q.values,[['1'],'2026-09-23','2026-10-06']);return {rows:data};}};let result=await readTalabatGrowth(talabat(),db,now);assert.equal(result.rows[0].delta,-4900);assert.equal(result.rows[0].current.sales,3500);data.splice(0,1);result=await readTalabatGrowth(talabat(),db,now);assert.equal(result.rows[0].reason,'PREVIOUS_DAYS_MISSING');assert.equal(result.rows[0].previous.sales,null);assert.equal(result.rows[0].delta,null);const ambiguous=[...rows(),...rows().map(r=>({...r,source_key:'other'}))];await assert.rejects(readTalabatGrowth(talabat(),{query:async()=>({rows:ambiguous})},now),/SOURCE_AMBIGUOUS/);const wrong=rows().map(r=>({...r,sales:'99'}));await assert.rejects(readTalabatGrowth(talabat(),{query:async()=>({rows:wrong})},now),/SOURCE_UNCONFIRMED/);});
test('Keeta uses exact previous week and scoped IDs, never substitutes overlapping rolling snapshots',async()=>{const current={state:'SUCCESS',snapshot:{periodFrom:p.from,periodTo:p.to,comparisonFrom:p.previousFrom,comparisonTo:p.previousTo,observedAt:now.toISOString(),shops:[{shopId:'1',shopName:'Kabab Fareej — Barsha',business:{shop_income:'500',shop_valid_order_num:'10'}}]}};const result=await readKeetaGrowth(current,{query:async(q:any)=>{assert.deepEqual(q.values,[p.previousFrom,p.previousTo]);return {rows:[{payload:{periodFrom:p.previousFrom,periodTo:p.previousTo,shops:[{shopId:'1',business:{shop_income:'1200',shop_valid_order_num:'20'}},{shopId:'2',shopName:'Forbidden',business:{shop_income:'90000',shop_valid_order_num:'50'}}]}}]};}},now);assert.equal(result.rows.length,1);assert.equal(result.rows[0].delta,-700);assert.ok(!JSON.stringify(result).includes('Forbidden'));const missing=await readKeetaGrowth(current,{query:async()=>({rows:[]})},now);assert.equal(missing.rows[0].reason,'PREVIOUS_REPORT_MISSING');assert.equal(missing.rows[0].delta,null);});
test('Noon uses store dashboard sales and actual comparison dates, excludes partial, stale or unequal periods',()=>{const data:any={state:'SUCCESS',snapshot:{period:{startDate:p.from,endDate:p.to,comparisonStartDate:p.previousFrom,comparisonEndDate:p.previousTo},observedAt:now.toISOString(),reports:[{scope:'BRAND',dashboard:{}},{scope:'STORE',restaurantId:'R1',outletCode:'O1',storeName:'Branch',dashboard:{salesInsights:{mainInsights:{ordersCount:10,revenue:500},mainInsightsPrevious:{ordersCount:20,revenue:1200}}},items:[{revenue:99999}]}]}};assert.equal(readNoonGrowth(data,now).rows[0].delta,-700);data.snapshot.period.endDate='2026-10-07';assert.equal(readNoonGrowth(data,now).rows[0].eligible,false);data.snapshot.period.endDate=p.to;data.snapshot.observedAt='2026-10-03T09:00:00Z';assert.equal(readNoonGrowth(data,now).rows[0].reason,'COLLECTION_STALE');});
test('Growth scopes before comparing and isolates failed platforms without leaking errors',async()=>{const user:any={role:'viewer'},calls:string[]=[];const result=await fetchGrowth(user,{NOON_RATINGS_ENABLED:'false'},fetch,{now,db:{query:async(q:any)=>{assert.deepEqual(q.values[0],['1']);return {rows:rows()};}},talabat:async()=>({...talabat(),rows:[...talabat().rows,{storeId:'2'}]}),scopeTalabat:async(d:any,u:any)=>{assert.equal(u,user);calls.push('scoped');return {...d,rows:d.rows.filter((r:any)=>r.storeId==='1')};},keeta:async()=>{throw Error('SECRET_SESSION');},noon:async()=>assert.fail('disabled Noon must not be fetched')});assert.deepEqual(calls,['scoped']);assert.equal(result.platforms[0].rows.length,1);assert.equal(result.platforms[1].state,'ERROR');assert.equal(result.platforms[2].state,'DISABLED');assert.ok(!JSON.stringify(result).includes('SECRET_SESSION'));});
test('Growth UI gross-decline denominator does not net off growth and null percentages sort last',()=>{const context=vm.createContext({Intl,escapeHtml:(v:any)=>String(v)});vm.runInContext(fs.readFileSync('public/growth.js','utf8'),context);context.rows=[growthRow('1','one',p,{sales:500,orders:10},{sales:1000,orders:20}),growthRow('2','two',p,{sales:900,orders:10},{sales:500,orders:10}),growthRow('3','three',p,{sales:100,orders:2},{sales:0,orders:0}),growthRow('4','four',p,{sales:null,orders:null},{sales:10000,orders:100})];assert.equal(vm.runInContext('GrowthCore.summary(rows).loss',context),500);assert.equal(vm.runInContext('GrowthCore.summary(rows).current-GrowthCore.summary(rows).previous',context),0);assert.equal(vm.runInContext('GrowthCore.summary(rows).excluded',context),1);assert.equal(vm.runInContext("GrowthCore.sort(rows.filter(r=>r.eligible),'percent').at(-1).identity",context),'3');});
test('Growth endpoint requires authentication and rejects extra query parameters before loading data',async()=>{const request:any={method:'GET',url:'/api/dashboard/performance/latest?dataset=growth',headers:{}};let body='';const response:any={statusCode:0,setHeader(){},end(v:string){body=v;}};await createCloudHandler('performance',{},fetch,async(_req,res)=>{res.statusCode=401;res.end('{}');return null;})(request,response);assert.equal(response.statusCode,401);request.url+='&date=2026-10-06';await createCloudHandler('performance',{},fetch,async()=>({role:'admin'} as any))(request,response);assert.equal(response.statusCode,400);assert.match(body,/Invalid Growth/);});

const noOrders=()=>({present:true,sales:null,orders:null,metrics:{...Object.fromEntries(['Gross Sales','Successful Orders','Orders count','Cancelled Orders','Online Sales','Cash Sales','Delivery Sales','Pickup Sales','Online Orders','Cash Orders','Delivery Orders','Pickup Orders','Pro Orders','Pro Revenue','Items count'].map(k=>[k,null])),'Placed an order':'0','Impressions':'1714','Viewed your menu':'83','Scheduled Open Time (Minutes)':'719.9833333333333'}});
test('Confirmed Talabat no-order pattern counts as a daily zero only in Growth',async()=>{
 const history:any[]=rows();history[10]={...history[10],...noOrders()};const before=JSON.stringify(history);
 const result=await readTalabatGrowth(talabat(),{query:async()=>({rows:history})},now);
 assert.equal(result.rows[0].eligible,true);assert.equal(result.rows[0].current.sales,3000);assert.equal(result.rows[0].current.orders,60);assert.equal(JSON.stringify(history),before);
});
test('Talabat zero-day rule excludes absent, partial, contradictory and unobserved rows',()=>{
 assert.equal(talabatZeroOrderDay(noOrders()),true);
 for(const change of [{present:false},{metrics:null},{sales:'100'},{orders:'1'}])assert.equal(talabatZeroOrderDay({...noOrders(),...change}),false);
 for(const change of [{'Placed an order':null},{'Placed an order':'1'},{'Orders count':'1'},{'Cancelled Orders':'1'},{'Cash Sales':'10'},{'Cash sales':'10'},{'Online sales':'5'},{'Online Orders':'bad'},{'Scheduled Open Time (Minutes)':'0'},{'Impressions':null,'Viewed your menu':null}])assert.equal(talabatZeroOrderDay({...noOrders(),metrics:{...noOrders().metrics,...change}}),false);
});
test('Incomplete Talabat row stays excluded when no-order evidence is absent',async()=>{
 const history:any[]=rows();history[10]={...history[10],sales:null,orders:null};
 const result=await readTalabatGrowth(talabat(),{query:async()=>({rows:history})},now);assert.equal(result.rows[0].reason,'CURRENT_DAYS_MISSING');
});
