import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {scopeKeetaSnapshot} from '../src/services/keeta-snapshot-scope.ts';
import {fetchKeetaPerformance} from '../src/services/performance-proxy.ts';
const fixture=()=>({periodFrom:'2026-09-28',periodTo:'2026-10-04',comparisonFrom:'2026-09-21',comparisonTo:'2026-09-27',shops:[{shopId:'1',shopName:'Same name'},{shopId:'2',shopName:'Same name'}],customers:{pay:[{code:'shop_brand_txn_user_num',value:'1544'}],byShop:[{shopId:'1',pay:[{code:'shop_txn_user_num',value:'124'},{code:'shop_new_user_num',value:'0'},{code:'shop_regular_user_num',value:'54'}]},{shopId:'2',pay:[]}]},items:[{shop_brand_product_info:'{"name":"Brand item"}',shop_brand_salevm:'1232'}],itemsByShop:[{shopId:'1',shopName:'Same name',total:1,complete:true,items:[{shop_product_new_name:'{"name":"Chicken <script>"}',shop_salevm:'103',shop_expose_uv:'1099',shop_product_avg_price:'58.73'}]},{shopId:'2',shopName:'Same name',total:0,complete:true,items:[]}],coverage:{items:true}});
function ui(){const c=vm.createContext({Intl,escapeHtml:(s:string)=>s.replace(/[&<>"']/g,(c:string)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)),storeIdentity:(s:any)=>({displayName:s.storeName})});vm.runInContext(fs.readFileSync(new URL('../public/keeta-performance.js',import.meta.url),'utf8'),c);return {run:(s:string)=>vm.runInContext(s,c),set:(s:any)=>{c.snap=s;}};}
test('branch Customers uses shop codes, retains zero and all eleven cards without brand fallback',()=>{const u=ui();u.set(fixture());u.run("keetaPerformanceState.customerShop='1'");const html=u.run('kpCustomers(snap)');assert.equal((html.match(/class="kpi-card"/g)||[]).length,11);assert.match(html,/>124</);assert.match(html,/>0</);assert.doesNotMatch(html,/>1544</);assert.equal((html.match(/Data unavailable/g)||[]).length,8);u.run("keetaPerformanceState.customerShop='2'");assert.equal((u.run('kpCustomers(snap)').match(/Data unavailable/g)||[]).length,11);});
test('branch Items selects exact IDs despite duplicate names and uses branch metrics',()=>{const u=ui();u.set(fixture());assert.match(u.run('kpItems(snap)'),/1232/);u.run("keetaPerformanceState.itemShop='1'");const html=u.run('kpItems(snap)');assert.match(html,/1099/);assert.match(html,/103/);assert.match(html,/58.73/);assert.match(html,/Chicken &lt;script&gt;/);assert.doesNotMatch(html,/1232|<script>/);u.run("keetaPerformanceState.search='chicken'");assert.match(u.run('kpItems(snap)'),/1 of 1/);u.run("keetaPerformanceState.itemShop='2'");assert.match(u.run('kpItems(snap)'),/No items for the selected branch scope/);});
test('legacy, incomplete and invalid selections never substitute brand rows',()=>{const u=ui(),s:any=fixture();s.itemsByShop=[];u.set(s);u.run("keetaPerformanceState.itemShop='1'");assert.match(u.run('kpItems(snap)'),/has not been collected/);assert.doesNotMatch(u.run('kpItems(snap)'),/1232/);s.itemsByShop=[{shopId:'1',items:[],complete:false,total:112}];assert.match(u.run('kpItems(snap)'),/incomplete: 0 of 112/);u.run("keetaPerformanceState.itemShop='999'");assert.match(u.run('kpItems(snap)'),/1232/);});
test('restricted branch scope removes foreign customer and item datasets and brand aggregates',()=>{const result=scopeKeetaSnapshot(fixture(),new Set(['1','999']));assert.equal(result.brandScopeAvailable,false);assert.equal(result.shops.length,1);assert.deepEqual(result.items,[]);assert.deepEqual(result.customers.pay,[]);assert.deepEqual(result.customers.byShop.map((s:any)=>s.shopId),['1']);assert.deepEqual(result.itemsByShop.map((s:any)=>s.shopId),['1']);const empty=scopeKeetaSnapshot(fixture(),new Set());assert.equal(empty.itemsByShop.length,0);const full=scopeKeetaSnapshot(fixture(),new Set(['1','2']));assert.equal(full.brandScopeAvailable,true);assert.equal(full.items.length,1);const u=ui();u.set(result);assert.doesNotMatch(u.run('kpItems(snap)'),/value="all"|value="2"|1232/);});
const config={ratingsApiUrl:'https://ratings.example/api/ratings/latest',ratingsApiToken:'x'.repeat(40)};
async function fetchSnapshot(s:any){return fetchKeetaPerformance(config,async()=>new Response(JSON.stringify({ok:true,platform:'keeta',state:'SUCCESS',snapshot:s}),{headers:{'content-type':'application/json'}}));}
test('proxy accepts new and legacy snapshots but rejects invalid branch payloads',async()=>{await fetchSnapshot(fixture());const legacy:any=fixture();delete legacy.itemsByShop;await fetchSnapshot(legacy);for(const mutate of [(s:any)=>s.itemsByShop[0].shopId='999',(s:any)=>s.itemsByShop.push(s.itemsByShop[0]),(s:any)=>s.itemsByShop[0].total=2,(s:any)=>s.itemsByShop[0].items=[null]]){const s=fixture();mutate(s);await assert.rejects(fetchSnapshot(s),/unavailable/);}});
