import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {scopeKeetaSnapshot} from '../src/services/keeta-snapshot-scope.ts';
import {fetchKeetaPerformance} from '../src/services/performance-proxy.ts';
const fixture=()=>({periodFrom:'2026-09-28',periodTo:'2026-10-04',comparisonFrom:'2026-09-21',comparisonTo:'2026-09-27',shops:[{shopId:'1',shopName:'Same name'},{shopId:'2',shopName:'Same name'}],customers:{pay:[{code:'shop_brand_txn_user_num',value:'1544'}],byShop:[{shopId:'1',pay:[{code:'shop_merchant_txn_user_num',value:'124'},{code:'shop_merchant_new_user_num',value:'0'},{code:'shop_merchant_regular_user_num',value:'54'}]},{shopId:'2',pay:[]}]},items:[{shop_brand_product_info:'{"name":"Brand item"}',shop_brand_salevm:'1232'}],itemsByShop:[{shopId:'1',shopName:'Same name',total:1,complete:true,items:[{shop_product_new_name:'{"name":"Chicken <script>"}',shop_salevm:'103',shop_expose_uv:'1099',shop_product_avg_price:'58.73'}]},{shopId:'2',shopName:'Same name',total:0,complete:true,items:[]}],coverage:{items:true}});
function ui(){const c=vm.createContext({Intl,escapeHtml:(s:string)=>s.replace(/[&<>"']/g,(c:string)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)),storeIdentity:(s:any)=>({displayName:s.storeName})});vm.runInContext(fs.readFileSync(new URL('../public/keeta-performance.js',import.meta.url),'utf8'),c);return {run:(s:string)=>vm.runInContext(s,c),set:(s:any)=>{c.snap=s;}};}
test('branch customer overview preserves zero, includes comparisons and charts without brand fallback',()=>{const u=ui();u.set(fixture());u.run("keetaPerformanceState.customerShop='1'");const html=u.run('kpCustomers(snap)');assert.equal((html.match(/class="kpi-card"/g)||[]).length,4);assert.match(html,/>124</);assert.match(html,/>0</);assert.doesNotMatch(html,/>1544</);assert.match(html,/Conversion funnel/);assert.match(html,/30 days/);u.run("keetaPerformanceState.customerMode='table'");const table=u.run('kpCustomers(snap)');assert.match(table,/Visible columns/);assert.equal((table.match(/<tr>/g)||[]).length,3);assert.doesNotMatch(table,/>1544</);});
test('branch Items selects exact IDs despite duplicate names and uses branch metrics',()=>{const u=ui();u.set(fixture());assert.match(u.run('kpItems(snap)'),/1232/);u.run("keetaPerformanceState.itemShop='1'");const html=u.run('kpItems(snap)');assert.match(html,/1099/);assert.match(html,/103/);assert.match(html,/58.73/);assert.match(html,/Chicken &lt;script&gt;/);assert.doesNotMatch(html,/1232|<script>/);u.run("keetaPerformanceState.search='chicken'");assert.match(u.run('kpItems(snap)'),/1 of 1/);u.run("keetaPerformanceState.itemShop='2'");assert.match(u.run('kpItems(snap)'),/No items for the selected branch scope/);});
test('legacy, incomplete and invalid selections never substitute brand rows',()=>{const u=ui(),s:any=fixture();s.itemsByShop=[];u.set(s);u.run("keetaPerformanceState.itemShop='1'");assert.match(u.run('kpItems(snap)'),/has not been collected/);assert.doesNotMatch(u.run('kpItems(snap)'),/1232/);s.itemsByShop=[{shopId:'1',items:[],complete:false,total:112}];assert.match(u.run('kpItems(snap)'),/incomplete: 0 of 112/);u.run("keetaPerformanceState.itemShop='999'");assert.match(u.run('kpItems(snap)'),/1232/);});
test('restricted branch scope removes foreign customer and item datasets and brand aggregates',()=>{const result=scopeKeetaSnapshot(fixture(),new Set(['1','999']));assert.equal(result.brandScopeAvailable,false);assert.equal(result.shops.length,1);assert.deepEqual(result.items,[]);assert.deepEqual(result.customers.pay,[]);assert.deepEqual(result.customers.byShop.map((s:any)=>s.shopId),['1']);assert.deepEqual(result.itemsByShop.map((s:any)=>s.shopId),['1']);const empty=scopeKeetaSnapshot(fixture(),new Set());assert.equal(empty.itemsByShop.length,0);const full=scopeKeetaSnapshot(fixture(),new Set(['1','2']));assert.equal(full.brandScopeAvailable,true);assert.equal(full.items.length,1);const u=ui();u.set(result);assert.doesNotMatch(u.run('kpItems(snap)'),/value="all"|value="2"|1232/);});
const config={ratingsApiUrl:'https://ratings.example/api/ratings/latest',ratingsApiToken:'x'.repeat(40)};
async function fetchSnapshot(s:any){return fetchKeetaPerformance(config,async()=>new Response(JSON.stringify({ok:true,platform:'keeta',state:'SUCCESS',snapshot:s}),{headers:{'content-type':'application/json'}}));}
test('proxy accepts new and legacy snapshots but rejects invalid branch payloads',async()=>{await fetchSnapshot(fixture());const legacy:any=fixture();delete legacy.itemsByShop;await fetchSnapshot(legacy);for(const mutate of [(s:any)=>s.itemsByShop[0].shopId='999',(s:any)=>s.itemsByShop.push(s.itemsByShop[0]),(s:any)=>s.itemsByShop[0].total=2,(s:any)=>s.itemsByShop[0].items=[null]]){const s=fixture();mutate(s);await assert.rejects(fetchSnapshot(s),/unavailable/);}});

// Exact codes and values supplied from the saved Al Barsha branch snapshot.
test('real merchant branch response fills all seven customer cards without aggregate fallback',()=>{
 const u=ui(),s=fixture();s.customers.byShop[0]={shopId:'1',pay:[{code:'shop_merchant_txn_user_num',value:'232'},{code:'shop_merchant_new_user_num',value:'127'},{code:'shop_merchant_regular_user_num',value:'105'}],frequency:[{code:'shop_merchant_repurchase_user_rate_30d',value:'31.46%'},{code:'shop_merchant_repurchase_user_num_30d',value:'73'},{code:'shop_merchant_1ord_user_rate_30d',value:'68.53%'},{code:'shop_merchant_1ord_user_num_30d',value:'159'},{code:'shop_merchant_2ord_user_rate_30d',value:'19.4%'},{code:'shop_merchant_2ord_user_num_30d',value:'45'},{code:'shop_merchant_3ord_plus_user_rate_30d',value:'12.07%'},{code:'shop_merchant_3ord_plus_user_num_30d',value:'28'}]} as any;
 u.set(s);u.run("keetaPerformanceState.customerShop='1'");const html=u.run('kpCustomers(snap)');
 for(const value of ['232','127','105','31.46%','68.53%','19.4%','12.07%'])assert.ok(html.includes('>'+value+'<'),value);
 assert.match(html,/Conversion funnel/);
 for(const value of ['1544','73','159','45','28'])assert.ok(!html.includes('>'+value+'<'),value);
 u.run("keetaPerformanceState.customerShop='all'");assert.match(u.run('kpCustomers(snap)'),/>1544</);
});

test('item sorting uses numeric values, puts unknowns last and breaks ties by name',()=>{
 const u=ui();u.run("keetaPerformanceState.itemSort='volume_desc'");assert.equal(u.run("kpCompareItems({shop_salevm:'100',shop_product_name:'B'},{shop_salevm:'20',shop_product_name:'A'},true)<0"),true);assert.equal(u.run("kpCompareItems({shop_salevm:'',shop_product_name:'A'},{shop_salevm:'0',shop_product_name:'B'},true)>0"),true);u.run("keetaPerformanceState.itemSort='conversion_asc'");assert.equal(u.run("kpCompareItems({shop_brand_avg_cartadd_cvr:'2.5%'},{shop_brand_avg_cartadd_cvr:'12.1%'},false)<0"),true);for(const value of [null,'','—','abc']){u.set({value});assert.equal(u.run('kpNum(snap.value)'),null);}assert.equal(u.run("kpNum('0')"),0);
});
test('Customer chart comparisons use percentage points, preserve unknowns and escape source values',()=>{
 const u=ui();u.set({pay:[{code:'shop_merchant_txn_user_num',value:'0',popValues:['0']}],conversion:[{code:'shop_entry_cartadd_cvr',value:'29%',popValues:['31%']},{code:'shop_expose_entry_cvr',value:'<script>',popValues:['10%']}]});const html=u.run('kpCustomerCharts(snap,true)');assert.match(html,/-2 pp/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);assert.match(html,/Largest measured conversion decline: Visit → cart/);
});

test('operational queue groups all breaches by exact shop ID while retaining low-volume policy',()=>{
 const u=ui();u.set([{shopId:'1',shopName:'Same',orders:100,cancelRate:3,offline:4,prep:19,missing:2},{shopId:'2',shopName:'Same',orders:10,cancelRate:3,offline:4,prep:19,missing:2}]);
 const rows=u.run('kpActions(snap)');assert.equal(rows.length,2);assert.equal(rows.find((r:any)=>r.shopId==='1').issues.length,4);assert.equal(rows.find((r:any)=>r.shopId==='2').issues.length,1);assert.match(u.run('kpOperations(snap,kpActions(snap))'),/kp-issue-badge/);
});
test('comparison color follows actual change, preserves zero and leaves unknowns neutral',()=>{
 const u=ui();assert.match(u.run("kpComparison({value:'0',popValues:['10'],popValue:'-100%'})"),/down/);assert.match(u.run("kpComparison({value:'10',popValues:['0'],popValue:'—'})"),/up/);assert.doesNotMatch(u.run("kpComparison({value:null,popValues:['10']})"),/kp-change/);assert.equal(u.run("kpDateRange('2026-10-01','2026-10-07')"),'1–7 Oct 2026');
});

test('customer exposure and funnel counts use source customer codes rather than item UV codes',()=>{
 const u=ui();u.set({conversion:[{code:'shop_expose_user_num',value:'55755',popValues:['50000']},{code:'shop_entry_user_num',value:'12965'},{code:'shop_cartadd_user_num',value:'3000'},{code:'shop_submit_user_num',value:'1600'},{code:'shop_pay_user_num',value:'1588'}]});assert.equal(u.run('kpCustomer(snap,true)[11].row.value'),'55755');assert.match(u.run('kpCustomerCharts(snap,true)'),/55755|12965|1588/);
});
