import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {readNoonSessionHealth} from '../src/services/noon-session-health.ts';
import {readNoonRatings} from '../src/services/noon-ratings.ts';
const snapshot=JSON.parse(fs.readFileSync('tests/fixtures/noon-snapshot.json','utf8'));
test('expired Noon session retains all saved ratings and snapshot date',async()=>{const db={query:async(q:any)=>({rows:q.text.includes('noon_session_health')?[{expired:true}]:[{payload:snapshot}]})};const data=await readNoonRatings(db);assert.equal(data.sessionHealth,'EXPIRED');assert.equal(data.state,'SUCCESS');assert.equal(data.ratings.length,22);assert.equal(data.syncTimestamp,snapshot.observedAt);});
test('health read handles recovery, no prior run and missing table without dropping snapshots',async()=>{assert.equal(await readNoonSessionHealth({query:async()=>({rows:[{expired:false}]})}),'OK');assert.equal(await readNoonSessionHealth({query:async()=>({rows:[]})}),'UNKNOWN');assert.equal(await readNoonSessionHealth({query:async()=>{throw Error('secret');}}),'UNKNOWN');});
test('Noon warning and health are driven by saved expiry, and disappear on recovery',()=>{const source=fs.readFileSync('public/app.js','utf8'),start=source.indexOf('function cloudHealth('),end=source.indexOf('function cloudPlatformCards(',start);const context=vm.createContext({timestamp:(s:string)=>Date.parse(s)});vm.runInContext(source.slice(start,end),context);assert.equal(vm.runInContext("cloudHealth({state:'SUCCESS',sessionHealth:'EXPIRED'})",context),'ERROR');assert.match(vm.runInContext("noonSessionWarning({sessionHealth:'EXPIRED'})",context),/role="alert"/);assert.equal(vm.runInContext("noonSessionWarning({sessionHealth:'OK'})",context),'');});

test('Performance reports keep saved metrics and show expiry even for an empty requested range',async()=>{const {readNoonPerformance}=await import('../src/services/noon-performance.ts');const performance=JSON.parse(fs.readFileSync('tests/fixtures/noon-performance-synthetic.json','utf8'));for(const payloads of [[],[{payload:performance}]]){const data=await readNoonPerformance({query:async(q:any)=>({rows:q.text.includes('noon_session_health')?[{expired:true}]:payloads})});assert.equal(data.sessionHealth,'EXPIRED');assert.equal(data.state,payloads.length?'SUCCESS':'EMPTY');if(payloads.length)assert.equal(data.snapshot.reports.length,24);}});
