import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {branchIdentity,allowedStore} from '../src/services/branch-identity.ts';
const context=vm.createContext({TextEncoder,Uint8Array,DataView,Date,Number});vm.runInContext(fs.readFileSync('public/ratings-export.js','utf8'),context);const api=context.RatingExports;
const groups=[{displayName:'Morwarid — Al Barsha',rows:[{platform:'talabat',rating:3.4,status:'CRITICAL',timestamp:'2026-10-06T06:00:00Z'},{platform:'keeta',rating:null,status:'UNKNOWN',timestamp:'2026-10-06T05:00:00Z'}]},{displayName:'Kabab Fareej — RAK',rows:[{platform:'talabat',rating:4.5,status:'HEALTHY',timestamp:'2026-10-06T06:00:00Z'},{platform:'keeta',rating:4.2,status:'WARNING',timestamp:'2026-10-06T05:00:00Z'}]}];
function entries(data:Uint8Array){const result=new Map<string,string>();const view=new DataView(data.buffer,data.byteOffset,data.byteLength);let offset=0;while(view.getUint32(offset,true)===0x04034b50){const length=view.getUint32(offset+18,true),nameLength=view.getUint16(offset+26,true),extra=view.getUint16(offset+28,true);const name=new TextDecoder().decode(data.slice(offset+30,offset+30+nameLength)),start=offset+30+nameLength+extra;result.set(name,new TextDecoder().decode(data.slice(start,start+length)));offset=start+length;}return result;}
test('selected platform export preserves visible row order, filters and missing ratings',()=>{const r=api.fromGroups([...groups].reverse(),{platform:'keeta',brand:'Morwarid',status:'WARNING',search:'RAK',generatedAt:'2026-10-06T06:00:00Z'});assert.equal(r.rows[0].branch,groups[1]!.displayName);assert.equal(r.rows[0].values[0],4.2);assert.equal(r.rows[1].values[0],null);assert.equal(r.columns.length,2);assert.ok(r.filters.includes('Morwarid'));assert.equal(r.observedAt,'2026-10-06T06:00:00Z');});
test('portfolio export retains separate actual platform ratings instead of a fabricated overall value',()=>{const r=api.fromGroups(groups);assert.deepEqual(Array.from(r.columns,(c:any)=>c.label),['Brand / branch','Talabat','Keeta']);assert.equal(r.rows[0].values[0],3.4);assert.equal(r.rows[0].values[1],null);});
test('Excel is a real styled OOXML workbook with numeric rating cells, frozen headers and repeat print titles',()=>{const r=api.fromGroups(groups,{platform:'talabat',generatedAt:'2026-10-06T06:00:00Z'}),files=entries(api.excel(r));assert.ok(files.has('[Content_Types].xml'));const sheet=files.get('xl/worksheets/sheet1.xml')!;assert.match(sheet,/<c r="C7" s="10"><v>3.4<\/v><\/c>/);assert.match(sheet,/>Brand</);assert.match(sheet,/>Location</);assert.match(sheet,/ySplit="6"/);assert.match(sheet,/autoFilter ref="A6:C8"/);assert.match(files.get('xl/styles.xml')!,/12243A/);assert.match(files.get('xl/workbook.xml')!,/_xlnm.Print_Titles/);});
test('exported names are literal text, not formulas or XML markup',()=>{const g=[{displayName:'=HYPERLINK("bad") <script> & كباب',rows:[{platform:'talabat',rating:null,status:'UNKNOWN'}]}],files=entries(api.excel(api.fromGroups(g,{platform:'talabat'}))),sheet=files.get('xl/worksheets/sheet1.xml')!;assert.ok(!sheet.includes('<f>'));assert.ok(!sheet.includes('<script>'));assert.match(sheet,/t="inlineStr"/);assert.match(sheet,/&lt;script&gt;/);assert.match(sheet,/كباب/);assert.match(sheet,/>—</);});
test('Morwarid naming preserves legacy branch identity and brand access assignments',()=>{const a=branchIdentity('Al Morwarid Restaurant - Al Barsha'),b=branchIdentity('Morwarid - Al Barsha'),c=branchIdentity('Marwareed - Al Barsha');assert.equal(a.key,b.key);assert.equal(a.key,c.key);assert.equal(a.key,'marwareed|al barsha');assert.ok(allowedStore({role:'brand_manager',scopes:[{type:'brand',key:'Marwareed'}]} as any,'Morwarid - Al Barsha'));});
test('frontend Morwarid display uses the same persisted key as server scope checks',()=>{const script=fs.readFileSync('public/app.js','utf8');const segment=script.slice(script.indexOf('const brandRules'),script.indexOf('function groupCloudRows'));const c=vm.createContext({});vm.runInContext(fs.readFileSync('public/branch-labels.js','utf8'),c);vm.runInContext(segment+';globalThis.identify=storeIdentity',c);const r=c.identify({storeName:'Marwareed - Al Barsha'});assert.equal(r.brand,'Morwarid');assert.equal(r.displayName,'Morwarid — Barsha');assert.equal(r.key,branchIdentity('Marwareed - Al Barsha').key);});

test('UI branch aliases apply exactly the requested spellings, while identity keys remain unchanged',()=>{
 const script=fs.readFileSync('public/app.js','utf8'),segment=script.slice(script.indexOf('const brandRules'),script.indexOf('function groupCloudRows')),c=vm.createContext({});vm.runInContext(fs.readFileSync('public/branch-labels.js','utf8'),c);vm.runInContext(segment+';globalThis.identify=storeIdentity',c);
 const aliases=[['Aweer, Ras Al Khor Industrial Area3','Aweer'],['Ras Al Khor Industrial Area 3','Aweer'],['Al Noof','Hoshi'],['Hay Hoshi','Hoshi'],["Al Bdai'a Subrub",'Hoshi'],['Al Dhait South','RAK'],['Al Dhait - RAK, Al Dhait South','RAK'],['RAK','RAK'],['Al Barsha 1','Barsha'],['Al Barsha','Barsha'],['Al Hamidiya 2','Ajman'],['Ajman','Ajman'],['Al Darfrah','AbuDhabi'],['Al Dafrah','AbuDhabi'],['Mushrif Mall, Al Dafrah','AbuDhabi']];
 for(const [raw,display] of aliases){const r=c.identify({storeName:'Kabab Fareej — '+raw});assert.equal(r.branch,display,raw);assert.equal(r.displayName,'Kabab Fareej — '+display);assert.equal(r.key,branchIdentity('Kabab Fareej — '+raw).key,raw);}
 assert.equal(c.BranchLabels.branch('Al Warqa'),'Al Warqa');
 assert.equal(c.BranchLabels.full('Marwareed — Al Barsha'),'Morwarid — Barsha');
 const a=c.identify({storeName:'Kabab Fareej — Al Noof'}),b=c.identify({storeName:'Kabab Fareej — Hay Hoshi'});assert.equal(a.displayName,b.displayName);assert.notEqual(a.key,b.key);
});
